### PR TITLE
API data gathered and written to both the database and csv file

### PR DESCRIPTION
**Pull request by audreynaidu**
i created a script that is able to use the instagram API to gather post data. Currently, it can gather date, post link, # likes, and # comments. It also has a unique post id within the database. I also created some basic buttons on the homepage that adds the most recent posts to the database, and another button that writes the entire database to a csv file. I made this csv file downloadable attachment so that when the button is clicked, the csv file will automatically download in the browser. When adding to the database, I implemented a duplication check where I check if the post link already exists in the database. I also added a text input area on the website that allows for manual input of the API key. 

rev1: this API key is now added to an API key model in the database. there can only be one instance of it at once and anytime a user inputs a new api key, it deletes the old instance, but the same user will only have to enter it once if it is valid.

### CODE REVIEW

**Comment by cbollsandiego** [comment]
Hey Audrey, it looks like the code is not passing the tests on Github Actions. The things that this code does looks awesome and I am glad that you were able to get it working but just need to make sure it is passing tests before merging into main. We also talked in class today about how we need proper docstrings for all the public functions that we make, I think this would include the functions in views.py and the two util .py files and then probably the JS equivalent of docstrings in the index.html.

**Comment by bilguuneo** [comment]
Great job working on the code, seems that everything works good now that we figured out the linting and the github actions.

**Review by bilguuneo — APPROVED** [review]
The code looks great. It seems that it is running as intended after fixing the issue and all the tests are passing

**Comment by audreynaidu** [comment]
[Implement functions to process data received from Instagram and put the data into the database correctly](https://trello.com/c/UHaYIKKl/15-implement-functions-to-process-data-received-from-instagram-and-put-the-data-into-the-database-correctly)

**Pull request merged**
